### ISSUE TITLE
make logs smaller, not to echo whole payload

### ISSUE THREAD

**Issue by jhutar** [RedHatInsights/platform-receptor-controller#95]
When I was running tests with Stresstest, I have noticed Receptor Controller log contains whole response. This makes logs huge and slightly less usable when testing with big messages (like 512kB) while the actual content is usually not that important I think.

**Comment by dehort** [comment]
This should be fixed as part of PR #89.

The log level can be set by using the RECEPTOR_CONTROLLER_LOG_LEVEL environment variable (set it to INFO, DEBUG, TRACE, etc).
